### ISSUE TITLE
Native: Issue with map key

### ISSUE THREAD

**Issue by melloware** [quarkiverse/quarkus-omnifaces#115]
Running in Native mode: https://issues.apache.org/jira/browse/MYFACES-4626

```
org.apache.myfaces.view.facelets.el.ContextAwarePropertyNotFoundException: jakarta.el.PropertyNotFoundException: The class 'org.apache.myfaces.util.lang.AbstractThreadSafeAttributeMap$EntrySetEntry' does not have the property 'key'.
766	at org.apache.myfaces.view.facelets.el.ContextAwareTagValueExpression.getValue(ContextAwareTagValueExpression.java:104)
767	at org.apache.myfaces.view.facelets.el.ELText$ELTextVariable.writeText(ELText.java:238)
768	at org.apache.myfaces.view.facelets.compiler.TextInstruction.write(TextInstruction.java:45)
769	at org.apache.myfaces.view.facelets.compiler.UIInstructions.encodeBegin(UIInstructions.java:46)
770	at org.apache.myfaces.view.facelets.compiler.UILeaf.encodeAll(UILeaf.java:362)
771	at org.apache.myfaces.view.facelets.component.RepeatRenderer.encodeChildren(RepeatRenderer.java:78)
772	at org.apache.myfaces.view.facelets.component.UIRepeat.process(UIRepeat.java:1056)
773	at org.apache.myfaces.view.facelets.component.UIRepeat.encodeChildren(UIRepeat.java:1698) 
```

**Comment by melloware** [comment]
Temporarily disabled native build until we can figure this issue out with MyFaces.

https://github.com/quarkiverse/quarkus-omnifaces/commit/850d9c97d5b63050d7212f900c66a2126d7d6ac5

**Comment by melloware** [comment]
added `classNames.addAll(collectImplementors(combinedIndex, Map.Entry.class.getName()));` to make it work properly  Made same fix in MyFaces
